name = "spingranny-casino-cz"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spingranny-casino.cz"
HMAC_KEY = "fa761f1b2093cc6d7f19d4b73aa6fa89ef960f64ba97e7506ee9c27cd0e2887d"
COOKIE_NAME = "t6i"
PLAY_PATH = "try"
BUTTON_ID = "p0e5e17fe55e8238c103fa8c095816ead"
GATE_SALT = "b2e9a480d442ca7b"
